---

- hosts: all

  roles:
  - role: jpic.ansible
    ansible_roles:
      jpic.ansible: https://github.com/jpic/jpic.ansible.git
      jpic.superadmin: https://github.com/jpic/jpic.superadmin.git
    tags: ansible

- hosts: all

  roles:
  - role: package
    become: yes
    package_list:
    - name: git
    - name: vim
